# Generated by Django 2.1.1 on 2020-03-28 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_Date', models.DateTimeField()),
                ('End_Date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NId', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('tz', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['NId'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='U_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.User'),
        ),
    ]
