# Generated by Django 2.1.1 on 2020-03-28 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20200328_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_Date', models.DateTimeField()),
                ('End_Date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='End_Date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Start_Date',
        ),
        migrations.AddField(
            model_name='activity',
            name='U_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.User'),
        ),
    ]
