# Generated by Django 2.1.1 on 2020-03-29 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20200328_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='U_ID',
        ),
        migrations.AddField(
            model_name='user',
            name='sm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='snippets.Activity'),
            preserve_default=False,
        ),
    ]
