# Generated by Django 2.1.1 on 2020-03-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20200329_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
