# Generated by Django 2.1.1 on 2020-03-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_auto_20200329_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nid',
            new_name='vat_id',
        ),
    ]
