# Generated by Django 2.1.1 on 2020-03-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_auto_20200329_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tz',
            new_name='address',
        ),
    ]
